### ISSUE TITLE
Error while starting server

### ISSUE THREAD

**Issue by ghoshdipan** [insidesherpa/JPMC-tech-task-2-PY3#128]
Traceback (most recent call last):
  File "datafeed/server3.py", line 320, in <module>
    run(App())
  File "datafeed/server3.py", line 214, in run
    server = ThreadedHTTPServer((host, port), RequestHandler)
  File "/usr/lib/python3.7/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.7/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.7/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
dipan@dipan-Lenovo-ideapad-330-15IKB:~/JPMC
.
.
.
.
Error while starting the server. Any suggestions

**Comment by rahulsingh2301** [comment]
try changing server.py(server3.py in case of python3) file port no. 8080 to 8085 and save the file and tray again.

**Comment by SiddhlodaAyyar** [comment]
Watch this video and if you still get the error comment down in the youtube section and we'll try to solve it.
https://youtu.be/wRAG9i8O_44
