### ISSUE TITLE
Most of packages are outdated for python 3

### ISSUE THREAD

**Issue by Prakhar998** [insidesherpa/JPMC-tech-task-2-PY3#133]
python3 server3.py
Traceback (most recent call last):
  File "server3.py", line 37, in <module>
    from http.server.HTTPServer import BaseHTTPRequestHandler,HTTPServer
ModuleNotFoundError: No module named 'http.server.HTTPServer'; 'http.server' is not a package
┌─[✗]─[prakhar@parrot]─[~/JPMC-tech-task-2-PY3/datafeed]
└──╼ $python3 server3.py
Traceback (most recent call last):
  File "server3.py", line 38, in <module>
    from SocketServer   import ThreadingMixIn
ModuleNotFoundError: No module named 'SocketServer'
┌─[✗]─[prakhar@parrot]─[~/JPMC-tech-task-2-PY3/datafeed]
└──╼ $python3 server3.py
Traceback (most recent call last):
  File "server3.py", line 38, in <module>
    from socketServer   import ThreadingMixIn
ModuleNotFoundError: No module named 'socketServer'
┌─[✗]─[prakhar@parrot]─[~/JPMC-tech-task-2-PY3/datafeed]
└──╼ $python3 server3.py
Traceback (most recent call last):
  File "server3.py", line 316, in <module>
    run(App())
  File "server3.py", line 246, in __init__
    self._sim_start, _, _ = self._data_1.next()
AttributeError: 'generator' object has no attribute 'next'

**Comment by SiddhlodaAyyar** [comment]
Watch this video and if you still get the error comment down in the youtube section and we'll try to solve it.
https://youtu.be/wRAG9i8O_44
