### ISSUE TITLE
Nothing showing after typing following command

### ISSUE THREAD

**Issue by kamyap** [insidesherpa/JPMC-tech-task-2-PY3#158]
python3 datafeed/server3.py

Please tell me how i canget the required output

**Comment by Rupesh-rkgit** [comment]
use python datafeed/server3.py instead

**Comment by LordUttam** [comment]
@kamyap If you have both python 2 and python 3 installed in your system, then `python3 datafeed/server3.py` is ok otherwise drop the 3 in python3. Also you have to execute that command in the "JPMC-tech-task-2-PY3 folder". I assume you are on windows.

**Comment by emmanuel-jr** [comment]
Use ```python``` not ```python3``` whether you have any python 2.x version as well.
I speak from experience
```python datafeed/server3.py``` - on python 3.x versions
```python datafeed/server.py``` - on python 2.x versions

**Comment by kamyap** [comment]
On typing this command -python datafeed/server3.py
the following error is showing up now
Traceback (most recent call last):
  File "datafeed/server3.py", line 320, in <module>
    run(App())
  File "datafeed/server3.py", line 214, in run
    server = ThreadedHTTPServer((host, port), RequestHandler)
  File "C:\Users\kamya\AppData\Local\Programs\Python\Python37\lib\socketserver.py", line 452, in __init__
    self.server_bind()
  File "C:\Users\kamya\AppData\Local\Programs\Python\Python37\lib\http\server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "C:\Users\kamya\AppData\Local\Programs\Python\Python37\lib\socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

**Comment by emmanuel-jr** [comment]
> On typing this command -python datafeed/server3.py
> the following error is showing up now
> Traceback (most recent call last):
>   File "datafeed/server3.py", line 320, in <module>
>     run(App())
>   File "datafeed/server3.py", line 214, in run
>     server = ThreadedHTTPServer((host, port), RequestHandler)
>   File "C:\Users\kamya\AppData\Local\Programs\Python\Python37\lib\socketserver.py", line 452, in __init__
>     self.server_bind()
>   File "C:\Users\kamya\AppData\Local\Programs\Python\Python37\lib\http\server.py", line 137, in server_bind
>     socketserver.TCPServer.server_bind(self)
>   File "C:\Users\kamya\AppData\Local\Programs\Python\Python37\lib\socketserver.py", line 466, in server_bind
>     self.socket.bind(self.server_address)
> OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

@kamyap do you mind sending a screenshot?

**Comment by kamyap** [comment]
![er](https://user-images.githubusercontent.com/65039322/81468546-d97fb480-91fd-11ea-891a-ca2d6f56e6b4.PNG)
yeah sure

**Comment by emmanuel-jr** [comment]
Did you go through the troubleshootings from the task?

**Comment by SiddhlodaAyyar** [comment]
Watch this video and if you still get the error comment down in the youtube section and we'll try to solve it.
https://youtu.be/wRAG9i8O_44
