### ISSUE TITLE
error while running "npm install"

### ISSUE THREAD

**Issue by Taekwonm** [insidesherpa/JPMC-tech-task-2-PY3#177]
I get the following error while trying to run "npm install". I have already tried the "npm config set python <path>" fix, but it didn't work. The error is as follows:

```
C:\Users\Natha\Documents\jpmorgan chase\JPMC-tech-task-2-PY3>npm install

> bufferutil@3.0.5 install C:\Users\Natha\Documents\jpmorgan chase\JPMC-tech-task-2-PY3\node_modules\bufferutil
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=11.0.0 runtime=node arch=x64 platform=win32)

C:\Users\Natha\Documents\jpmorgan chase\JPMC-tech-task-2-PY3\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Users\Natha\AppData\Roaming\nvm\v11.0.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Natha\AppData\Roaming\nvm\v11.0.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\Natha\AppData\Local\Programs\Python\Python38", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\Natha\AppData\Roaming\nvm\v11.0.0\node_modules\npm\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\Natha\AppData\Roaming\nvm\v11.0.0\node_modules\npm\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at C:\Users\Natha\AppData\Roaming\nvm\v11.0.0\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:161:21)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Natha\\AppData\\Roaming\\nvm\\v11.0.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Natha\Documents\jpmorgan chase\JPMC-tech-task-2-PY3\node_modules\bufferutil
gyp ERR! node -v v11.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN bootstrap@4.2.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.2.1 requires a peer of popper.js@^1.14.6 but none is installed. You must install peer dependencies yourself.
npm WARN extract-text-webpack-plugin@3.0.2 requires a peer of webpack@^3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bufferutil@3.0.5 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bufferutil@3.0.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Natha\AppData\Roaming\npm-cache\_logs\2020-05-10T01_35_23_249Z-debug.log
```

**Comment by SiddhlodaAyyar** [comment]
Watch this video and if you still get the error comment down in the section and we'll try to solve it.
https://youtu.be/wRAG9i8O_44

**Comment by khushi456** [comment]
Do this...it worked for me.
1. npm install --force
2. npm audit fund
3. npm start

**Comment by mryupyup** [comment]
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rah\AppData\Roaming\npm-cache\_logs\2020-05-16T12_35_06_681Z-debug.log
