### ISSUE TITLE
Error on running python3 datafeed/server3.py

### ISSUE THREAD

**Issue by Kam149** [insidesherpa/JPMC-tech-task-2-PY3#191]
When I run this the server.py on IDLE I get the following error: - 
**Traceback (most recent call last):
  File "C:\Users\Kamakshi\JPMC-tech-task-2-PY3\datafeed\server3.py", line 320, in <module>
    run(App())
  File "C:\Users\Kamakshi\JPMC-tech-task-2-PY3\datafeed\server3.py", line 244, in __init__
    self._sim_start, _, _  = next(self._data_1)
StopIteration**
I use python 3.7.2 .
Can anyone please tell me what to do now?

**Comment by Rupesh-rkgit** [comment]
can you attach the screenshot??

**Comment by Raj2367** [comment]
@Kam149 Use the command "python datafeed/server3.py" and if you are getting the same error again then change the port number 8080 to 8085 in server3.py using any text editor. otherwise, turn off your firewall for some time.

**Comment by SiddhlodaAyyar** [comment]
Watch this video and if you still get the error comment down in the youtube section and we'll try to solve it.
https://youtu.be/wRAG9i8O_44

**Comment by navreet1999** [comment]
> @Kam149 Use the command "python datafeed/server3.py" and if you are getting the same error again then change the port number 8080 to 8085 in server3.py using any text editor. otherwise, turn off your firewall for some time.

this is not working

**Comment by navreet1999** [comment]
your must be in JPMC-tech-task2-PY3 not in datafeed
and the run python datafeed/server3.py

**Comment by Aman22sharma** [comment]
@Kam149 I am also facing this same error. Have you resolved this error. Can you please share with me how can I resolve this, please?

**Comment by Kam149** [comment]
When I ran this on cmd, I didn't get any error. I got this error, when I directly ran server3 on IDLE. So, where are you running server3.

**Comment by Aman22sharma** [comment]
the same thing is was also doing that's why it shows error. I got the mistake and resolved it thank you

**Comment by Kam149** [comment]
@Aman22sharma so what was your mistake?

**Comment by Aman22sharma** [comment]
> When I ran this on cmd, I didn't get any error. I got this error, when I directly ran server3 on IDLE. So, where are you running server3.

@Kam149 The same issue

**Comment by Kam149** [comment]
Ok. Happy to help you.

**Comment by Aman22sharma** [comment]
@Kam149 can I have your social media profile or Whatsapp number so that I can reach out to you?

**Comment by Darknight471** [comment]
> When I run this the server.py on IDLE I get the following: -
> **Traceback (most recent call last): File "C:\Users\Kamakshi\JPMC-tech-task-2-PY3\datafeed\server3.py", line 320, in run(App()) File "C:\Users\Kamakshi\JPMC-tech-task-2-PY3\datafeed\server3.py", line 244, in **init** self._sim_start, _, _ = next(self._data_1) StopIteration**
> I use python 3.7.2 .
> Can anyone please tell me what does this mean?

try running the server by using 'python3 datafeed/server3.py
from JPMC-tech-task-2- folder.
Don't directly go to the directory of datafeed and run!

**Comment by Aman22sharma** [comment]
@Darknight471 You have to run python datafeed/server3.py inside the JPMC-tech-task2-folder then it will work properly
