### ISSUE TITLE
npm start: Error

### ISSUE THREAD

**Issue by vkmanojk** [insidesherpa/JPMC-tech-task-2-PY3#196]
I am able to run the python server at port 8080 however, when I run  
`npm start`
I get the following error:
```Attempting to bind to HOST environment variable: x86_64-conda_cos6-linux-gnu
If this was unintentional, check that you haven't mistakenly set it in your shell.
Learn more here: http://bit.ly/CRA-advanced-config

events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND x86_64-conda_cos6-linux-gnu
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:58:26)
Emitted 'error' event at:
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1466:12)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:58:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bank-merge-co-task-2@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bank-merge-co-task-2@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vkmanojk/.npm/_logs/2020-05-12T14_20_00_707Z-debug.log
```
This is the error log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/home/vkmanojk/.nvm/versions/node/v11.0.0/bin/node',
1 verbose cli   '/home/vkmanojk/.nvm/versions/node/v11.0.0/bin/npm',
1 verbose cli   'start' ]
2 info using npm@6.14.5
3 info using node@v11.0.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle bank-merge-co-task-2@0.1.0~prestart: bank-merge-co-task-2@0.1.0
6 info lifecycle bank-merge-co-task-2@0.1.0~start: bank-merge-co-task-2@0.1.0
7 verbose lifecycle bank-merge-co-task-2@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle bank-merge-co-task-2@0.1.0~start: PATH: /home/vkmanojk/.nvm/versions/node/v11.0.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/vkmanojk/JPMorgan/JPMC-tech-task-2-PY3/node_modules/.bin:/home/vkmanojk/.nvm/versions/node/v11.0.0/bin:/home/vkmanojk/anaconda3/bin:/home/vkmanojk/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle bank-merge-co-task-2@0.1.0~start: CWD: /home/vkmanojk/JPMorgan/JPMC-tech-task-2-PY3
10 silly lifecycle bank-merge-co-task-2@0.1.0~start: Args: [ '-c', 'react-scripts start' ]
11 silly lifecycle bank-merge-co-task-2@0.1.0~start: Returned: code: 1  signal: null
12 info lifecycle bank-merge-co-task-2@0.1.0~start: Failed to exec start script
13 verbose stack Error: bank-merge-co-task-2@0.1.0 start: `react-scripts start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/vkmanojk/.nvm/versions/node/v11.0.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/home/vkmanojk/.nvm/versions/node/v11.0.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid bank-merge-co-task-2@0.1.0
15 verbose cwd /home/vkmanojk/JPMorgan/JPMC-tech-task-2-PY3
16 verbose Linux 4.15.0-88-generic
17 verbose argv "/home/vkmanojk/.nvm/versions/node/v11.0.0/bin/node" "/home/vkmanojk/.nvm/versions/node/v11.0.0/bin/npm" "start"
18 verbose node v11.0.0
19 verbose npm  v6.14.5
20 error code ELIFECYCLE
21 error errno 1
22 error bank-merge-co-task-2@0.1.0 start: `react-scripts start`
22 error Exit status 1
23 error Failed at the bank-merge-co-task-2@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by cef1998** [comment]
If you have run command `npm init` , it has created `package.json` file at your current directory. Don't do that instead:

Goto **JPMC-tech-task-2-PY3** folder, if using python3.x(here you already have `package.json` file and it already contain dependencies needed) and run follwing command:
`npm install`     ignore any warnings.
`npm start`    it will start your server and  **http://localhost:3000/** will automatically opens up in browser.

Hope this resolve your problem.

**Comment by vkmanojk** [comment]
@cef1998  I am getting the same error,
```
> bank-merge-co-task-2@0.1.0 start /home/vkmanojk/JPMorgan/JPMC-tech-task-2-PY3
> react-scripts start

Attempting to bind to HOST environment variable: x86_64-conda_cos6-linux-gnu
If this was unintentional, check that you haven't mistakenly set it in your shell.
Learn more here: http://bit.ly/CRA-advanced-config

events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND x86_64-conda_cos6-linux-gnu
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:58:26)
Emitted 'error' event at:
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1466:12)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:58:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bank-merge-co-task-2@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bank-merge-co-task-2@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vkmanojk/.npm/_logs/2020-05-13T11_46_41_109Z-debug.log

```

**Comment by SiddhlodaAyyar** [comment]
Watch this video and if you still get the error comment down in the youtube section and we'll try to solve it.
https://youtu.be/wRAG9i8O_44

**Comment by Yash-Bhange** [comment]
also  after runnig server3.py and client3.py  , it shown output on cmd  but on localhost 3000 it show error . i have tried  port 8080, 8085, but nothing works

**Comment by vkmanojk** [comment]
The issue has been resolved when running the terminal as root.

**Comment by mryupyup** [comment]
npm start gives the following error in windows
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\aman\AppData\Roaming\npm-cache\_logs\2020-05-17T11_07_30_155Z-debug.log

**Comment by neilpatel12** [comment]
> @cef1998 I am getting the same error,
> 
> ```
> :~/JPMorgan/JPMC-tech-task-2-PY3$ npm start
> 
> > bank-merge-co-task-2@0.1.0 start /home/JPMorgan/JPMC-tech-task-2-PY3
> > react-scripts start
> 
> Attempting to bind to HOST environment variable: x86_64-conda_cos6-linux-gnu
> If this was unintentional, check that you haven't mistakenly set it in your shell.
> Learn more here: http://bit.ly/CRA-advanced-config
> 
> events.js:167
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: getaddrinfo ENOTFOUND x86_64-conda_cos6-linux-gnu
>     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:58:26)
> Emitted 'error' event at:
>     at GetAddrInfoReqWrap.doListen [as callback] (net.js:1466:12)
>     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:58:17)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! bank-merge-co-task-2@0.1.0 start: `react-scripts start`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the bank-merge-co-task-2@0.1.0 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/vkmanojk/.npm/_logs/2020-05-13T11_46_41_109Z-debug.log
> ```

Also have an identical error message, have you found a solution?

**Comment by neilpatel12** [comment]
> The issue has been resolved when running the terminal as root.

I have attempted this, however localhost will not open?
