### ISSUE TITLE
while running python/datafeed server3.py gives error(Traceback (most recent call last):   File "server3.py", line 320, in <module>     run(App())   File "server3.py", line 244, in __init__     self._sim_start, _, _  = next(self._data_1) StopIteration

### ISSUE THREAD

**Issue by navreet1999** [insidesherpa/JPMC-tech-task-2-PY3#209]
Traceback (most recent call last):
  File "server3.py", line 320, in <module>
    run(App())
  File "server3.py", line 244, in __init__
    self._sim_start, _, _  = next(self._data_1)
StopIteration

**Comment by manumohit** [comment]
I am facing same problem. Did you found solution for this?

**Comment by bhanuteja2001** [comment]
same issue here too!
But the server is working fine for TASK-3

**Comment by bhanuteja2001** [comment]
@manumohit and @navreet1999  
try running the server by using 'python datafeed/server3.py
Don't directly go to the directory of datafeed and run!

**Comment by harmankaur23** [comment]
I don't know if it would work for you, but I went to JPMC task1 folder and ran server3.py there instead, and npm start from the task 2 folder.
Weird but worked:)

**Comment by paragsahu03** [comment]
> @manumohit and @navreet1999
> try running the server by using 'python datafeed/server3.py
> Don't directly go to the directory of datafeed and run!

It worked for me

**Comment by haaskrishna18** [comment]
> > @manumohit and @navreet1999
> > try running the server by using 'python datafeed/server3.py
> > Don't directly go to the directory of datafeed and run!
> 
> It worked for me

 
it worked for me too!!
Thanks a lot brother!

**Comment by wkolee** [comment]
> @manumohit and @navreet1999
> try running the server by using 'python datafeed/server3.py
> Don't directly go to the directory of datafeed and run!

This work perfectly

**Comment by Huey-ZhangHaiyu** [comment]
> @bhanuteja2001 
> try running the server by using 'python datafeed/server3.py
> Don't directly go to the directory of datafeed and run!

but I uses python3 interpreter, why I can use 'python' instead of 'python3 datafeed/server3.py'

**Comment by RadientBrain** [comment]
> > @manumohit and @navreet1999
> > try running the server by using 'python datafeed/server3.py
> > Don't directly go to the directory of datafeed and run!
> 
> It worked for me

This worked for me too

**Comment by bhanuteja2001** [comment]
@Huey-ZhangHaiyu you can use python3 as well if it works for you.
The idea is to run server3.py

**Comment by withteja** [comment]
Check if python has been installed multiple times.
I got the same error and uninstalling python helped me solve this issue.
checkout this link if you are using mac https://stackoverflow.com/questions/36001966/unable-to-run-python-3-after-homebrew-installation

**Comment by Punit29** [comment]
> @manumohit and @navreet1999
> try running the server by using 'python datafeed/server3.py
> Don't directly go to the directory of datafeed and run!

weird but worked for me too thanks 👍 .

**Comment by vihan02** [comment]
> @manumohit and @navreet1999
> try running the server by using 'python datafeed/server3.py
> Don't directly go to the directory of datafeed and run!

this works

**Comment by prakharxyz** [comment]
> @manumohit and @navreet1999
> try running the server by using 'python datafeed/server3.py
> Don't directly go to the directory of datafeed and run!

it is not working!!!

**Comment by Yooosless** [comment]
> @manumohit and @navreet1999 try running the server by using 'python datafeed/server3.py Don't directly go to the directory of datafeed and run!

i love you

**Comment by souromisen** [comment]
> @manumohit and @navreet1999 try running the server by using 'python datafeed/server3.py Don't directly go to the directory of datafeed and run!

I tried this but it's still giving me an error:

C:\Users\SOUROMI SEN\JPMC-tech-task-2-PY3>python3 datafeed/server3.py
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

**Comment by adityakr38** [comment]
Hey, guys I used python datafeed/server3.py but it didn't worked it says Address already in use. Can someone help me please?

**Comment by bartotti** [comment]
> Hey, guys I used python datafeed/server3.py but it didn't worked it says Address already in use. Can someone help me please?

go to the forage-jpmc-swe-task-2$ and type "python3 datafeed/server3.py" or python datafeed/server3.py
hope this helps

**Comment by AghastyGD** [comment]
> 'python datafeed/server3.py

Thanks this worked for me

**Comment by hamza12529** [comment]
> @manumohit and @navreet1999 try running the server by using 'python datafeed/server3.py Don't directly go to the directory of datafeed and run!

works for me :)

**Comment by LuxExpanded** [comment]
![Screenshot](https://github.com/insidesherpa/JPMC-tech-task-2-PY3/assets/100960075/0b49e152-978f-45e3-b8cf-fff018610190)
I get this when I enter 'python datafeed/server3.py'

*update after I closed the program and reopened it, it worked fine

**Comment by hamza12529** [comment]
> ![Screenshot](https://private-user-images.githubusercontent.com/100960075/323029205-0b49e152-978f-45e3-b8cf-fff018610190.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzMTkzMDIsIm5iZiI6MTcxMzMxOTAwMiwicGF0aCI6Ii8xMDA5NjAwNzUvMzIzMDI5MjA1LTBiNDllMTUyLTk3OGYtNDVlMy1iOGNmLWZmZjAxODYxMDE5MC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxN1QwMTU2NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNGFlNmI0ZmQzNjhkYjhhZGRlNjQ0Mzc2OWUyMzk1MjU3MTY4M2U4NTBkMzI5ZWJlMDI2MDI1ZGViZDVkYjc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.reelDAvp8ktPbmfDzaAv2Cmi-g7dPFW8qaiVZUcBULA) I get this when I enter 'python datafeed/server3.py'
> 
> *update after I closed the program and reopened it, it worked fine

Either you dont have the compiler setup in the project or PATH in system variables.

1. Try to add python compiler in the project.
2. If above doesn’t work then See if python is added into the PATH.
3. If it is not added then try reinstalling python and check the box at the end to add PATH into system/ environment variable. (i dont remember the exact wording right now 😅)

**Comment by SakshamcodeX** [comment]
> @manumohit and @navreet1999 try running the server by using 'python datafeed/server3.py Don't directly go to the directory of datafeed and run!

its worked for me

**Comment by vibhasrik** [comment]
> @manumohit and @navreet1999 try running the server by using 'python datafeed/server3.py Don't directly go to the directory of datafeed and run!

Hmm, I ran my code like this and it seems like it is working, but the run is not finishing. I am not able to run "npm start" because the terminal is still running with the python datafeed/server3.py command. I tried with python and python3, but there is no difference.

<img width="826" alt="Screenshot 2024-06-19 at 3 15 40 PM" src="https://github.com/insidesherpa/JPMC-tech-task-2-PY3/assets/129092369/4a89fdad-b286-4a96-9a36-caa6359d89e2">

Edit: Nevermind, I made a silly mistake and forgot to run npm start in a different terminal.

**Comment by khlam0408** [comment]
> > @manumohit and @navreet1999 try running the server by using 'python datafeed/server3.py Don't directly go to the directory of datafeed and run!
> 
> Hmm, I ran my code like this and it seems like it is working, but the run is not finishing. I am not able to run "npm start" because the terminal is still running with the python datafeed/server3.py command. I tried with python and python3, but there is no difference.
> 
> <img alt="Screenshot 2024-06-19 at 3 15 40 PM" width="826" src="https://private-user-images.githubusercontent.com/129092369/341195229-4a89fdad-b286-4a96-9a36-caa6359d89e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NzYwMTgsIm5iZiI6MTcyMTY3NTcxOCwicGF0aCI6Ii8xMjkwOTIzNjkvMzQxMTk1MjI5LTRhODlmZGFkLWIyODYtNGE5Ni05YTM2LWNhYTYzNTlkODllMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMlQxOTE1MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NzkyYzcxYTlkNTcxMDA5NzVmNjhlNzc4NzZhODYxMmYzMzUxY2I4N2Y1MjhkYmQwYTI5NjViMDJjMDFkNzFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eaXNcV6tgV3zaufrCasrwIcMoSpPHa7UoXgbf38jyi0">
> Edit: Nevermind, I made a silly mistake and forgot to run npm start in a different terminal.

Im having this same issue, and I did try doing it separate terminals, but I still do not have access to port 8080

**Comment by zakard114** [comment]
> @manumohit and @navreet1999 try running the server by using 'python datafeed/server3.py Don't directly go to the directory of datafeed and run!

Thanks mate, you are my lifesaver!

I did this - 
PS E:\IT_SPACES\AutoProject\Forage\JPMorgan\forage-jpmc-swe-task-2> python datafeed/server3.py
