### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by Geethanjali910** [insidesherpa/JPMC-tech-task-2-PY3#287]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\ASUS\AppData\Roaming\nvm\v11.0.0\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ASUS\\AppData\\Roaming\\nvm\\v11.0.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\ASUS\JPMC-tech-task-2-PY3\node_modules\bufferutil
gyp ERR! node -v v12.16.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bufferutil@3.0.5 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!

**Comment by Kam149** [comment]
Instead of doing this: - Do this: -
There is another work around given in the slides .They provided a google
drive link to download a file and place it  in the folder and delete the existing **node_modules** file. After that you don't need to use npm install instead use directly npm start. That worked
for me. Search for it in troubleshoot section of the slides.

**Comment by mokshadoshi0701** [comment]
There was no folder named node_modules in my repo so I downloaded it from the given link in the pdf and extracted it in my repo. And then I used npm install command and it's showing me this error:
C:\Users\abc\AppData\Roaming\JPMC-tech-task-2-PY3>npm start

> bank-merge-co-task-2@0.1.0 start C:\Users\abc\AppData\Roaming\JPMC-tech-task-2-PY3
> react-scripts start

'react-scripts' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bank-merge-co-task-2@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bank-merge-co-task-2@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\abc\AppData\Roaming\npm-cache\_logs\2020-05-25T11_22_44_629Z-debug.log


what is the solution to this?
