### ISSUE TITLE
nvm install error

### ISSUE THREAD

**Issue by aartii05** [insidesherpa/JPMC-tech-task-2-PY3#315]
![Screenshot 2020-05-30 at 11 21 08 AM 1](https://user-images.githubusercontent.com/65904083/83320721-c34a9e80-a267-11ea-99b5-3cfa411ff633.png)

**Comment by rijulm** [comment]
I get the same weird error! They have a few slides on troubleshooting them I believe.

**Comment by rijulm** [comment]
Never mind, I figured it out. You need to cd into the directory you're working in! Worked for me.

**Comment by NihaHoney** [comment]
> Never mind, I figured it out. You need to cd into the directory you're working in! Worked for me.
 
Iam getting the same problem. Can you explain me clearly how to solve this.

**Comment by nitindang** [comment]
Same problem did you figure out yet ?

**Comment by MahimaJindalMJ** [comment]
> Never mind, I figured it out. You need to cd into the directory you're working in! Worked for me.

I have tried it, now it shows another error

C:\Users\Mahima\JPMC-tech-task-2-PY3>**npm start**

> bank-merge-co-task-2@0.1.0 start C:\Users\Mahima\JPMC-tech-task-2-PY3
> react-scripts start

'react-scripts' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bank-merge-co-task-2@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bank-merge-co-task-2@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mahima\AppData\Roaming\npm-cache\_logs\2020-06-07T12_59_29_788Z-debug.log

**Comment by nitindang** [comment]
I am getting this error 

C:\Users\Dell>**npm install**
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\Dell\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Dell\package.json'
npm WARN Dell No description
npm WARN Dell No repository field.
npm WARN Dell No README data
npm WARN Dell No license field.

audited 3 packages in 1.172s
found 0 vulnerabilities

C:\Users\Dell>**npm start**
npm ERR! path C:\Users\Dell\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\Dell\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\Dell\AppData\Roaming\npm-cache_logs\2020-06-07T13_01_43_729Z-debug.log

**Comment by nitindang** [comment]
> > Never mind, I figured it out. You need to cd into the directory you're working in! Worked for me.
> 
> I have tried it, now it shows another error
> 
> C:\Users\Mahima\JPMC-tech-task-2-PY3>**npm start**
> 
> > bank-merge-co-task-2@0.1.0 start C:\Users\Mahima\JPMC-tech-task-2-PY3
> > react-scripts start
> 
> 'react-scripts' is not recognized as an internal or external command,
> operable program or batch file.
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! bank-merge-co-task-2@0.1.0 start: `react-scripts start`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the bank-merge-co-task-2@0.1.0 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users\Mahima\AppData\Roaming\npm-cache_logs\2020-06-07T12_59_29_788Z-debug.log

Mahima in which directory you are running the command. Which has the build tools in it ??

**Comment by MahimaJindalMJ** [comment]
> > > Never mind, I figured it out. You need to cd into the directory you're working in! Worked for me.
> > 
> > 
> > I have tried it, now it shows another error
> > C:\Users\Mahima\JPMC-tech-task-2-PY3>**npm start**
> > > bank-merge-co-task-2@0.1.0 start C:\Users\Mahima\JPMC-tech-task-2-PY3
> > > react-scripts start
> > 
> > 
> > 'react-scripts' is not recognized as an internal or external command,
> > operable program or batch file.
> > npm ERR! code ELIFECYCLE
> > npm ERR! errno 1
> > npm ERR! bank-merge-co-task-2@0.1.0 start: `react-scripts start`
> > npm ERR! Exit status 1
> > npm ERR!
> > npm ERR! Failed at the bank-merge-co-task-2@0.1.0 start script.
> > npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> > npm ERR! A complete log of this run can be found in:
> > npm ERR! C:\Users\Mahima\AppData\Roaming\npm-cache_logs\2020-06-07T12_59_29_788Z-debug.log
> 
> Mahima in which directory you are running the command. Which has the build tools in it ??

No. I don't know exactly where Build tools installed in the PC as I used Visual Studio installer to install Visual Studio Build Tools 2019 (C++ Build Tools) and I think they are in _C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools._

![image](https://user-images.githubusercontent.com/35771912/83971550-7e72d780-a8f9-11ea-96b8-35cd991fc1db.png)

 I run the **npm start** command in the directory in which I cloned JPMC-tech-task-2-PY3 repository for task 2.
**Where you run it?**

**Comment by nitindang** [comment]
> > Mahima in which directory you are running the command. Which has the build tools in it ??
> 
> No. I don't know exactly where Build tools installed in the PC as I used Visual Studio installer to install Visual Studio Build Tools 2019 (C++ Build Tools) and I think they are in _C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools._
> 
> ![image](https://user-images.githubusercontent.com/35771912/83971550-7e72d780-a8f9-11ea-96b8-35cd991fc1db.png)
> 
> I run the **npm start** command in the directory in which I cloned JPMC-tech-task-2-PY3 repository for task 2.
> **Where you run it?**


I ran it in the JPMC task 2 directory now but I am still facing these issues 

C:\Users\Dell\JPMC-tech-task-2-PY3>npm install

> bufferutil@3.0.5 install C:\Users\Dell\JPMC-tech-task-2-PY3\node_modules\bufferutil
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=11.0.0 runtime=node arch=x64 platform=win32)

C:\Users\Dell\JPMC-tech-task-2-PY3\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Users\Dell\AppData\Roaming\nvm\v11.0.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Dell\AppData\Roaming\nvm\v11.0.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Traceback (most recent call last):
  File "C:\Users\Dell\AppData\Roaming\nvm\v11.0.0\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "C:\Users\Dell\AppData\Roaming\nvm\v11.0.0\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "C:\Users\Dell\AppData\Roaming\nvm\v11.0.0\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "C:\Users\Dell\AppData\Roaming\nvm\v11.0.0\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "C:\Users\Dell\AppData\Roaming\nvm\v11.0.0\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 98, in Load
    generator.CalculateVariables(default_variables, params)
  File "C:\Users\Dell\AppData\Roaming\nvm\v11.0.0\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1916, in CalculateVariables
    generator_flags.get('msvs_version', 'auto'))
  File "C:\Users\Dell\AppData\Roaming\nvm\v11.0.0\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\MSVSVersion.py", line 434, in SelectVisualStudioVersion
    versions = _DetectVisualStudioVersions(version_map[version], 'e' in version)
KeyError: '2019'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\Dell\AppData\Roaming\nvm\v11.0.0\node_modules\npm\node_modules\node-gyp\lib\configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Dell\\AppData\\Roaming\\nvm\\v11.0.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Dell\JPMC-tech-task-2-PY3\node_modules\bufferutil
gyp ERR! node -v v11.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN rollback Rolling back node-pre-gyp@0.10.0 failed (this is probably harmless): EPERM: operation not permitted, lstat 'C:\Users\Dell\JPMC-tech-task-2-PY3\node_modules\fsevents\node_modules'
npm WARN bootstrap@4.2.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.2.1 requires a peer of popper.js@^1.14.6 but none is installed. You must install peer dependencies yourself.
npm WARN extract-text-webpack-plugin@3.0.2 requires a peer of webpack@^3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bufferutil@3.0.5 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bufferutil@3.0.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dell\AppData\Roaming\npm-cache\_logs\2020-06-07T14_33_42_883Z-debug.log



> > > > Never mind, I figured it out. You need to cd into the directory you're working in! Worked for me.
> > > 
> > > 
> > > I have tried it, now it shows another error
> > > C:\Users\Mahima\JPMC-tech-task-2-PY3>**npm start**
> > > > bank-merge-co-task-2@0.1.0 start C:\Users\Mahima\JPMC-tech-task-2-PY3
> > > > react-scripts start
> > > 
> > > 
> > > 'react-scripts' is not recognized as an internal or external command,
> > > operable program or batch file.
> > > npm ERR! code ELIFECYCLE
> > > npm ERR! errno 1
> > > npm ERR! bank-merge-co-task-2@0.1.0 start: `react-scripts start`
> > > npm ERR! Exit status 1
> > > npm ERR!
> > > npm ERR! Failed at the bank-merge-co-task-2@0.1.0 start script.
> > > npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> > > npm ERR! A complete log of this run can be found in:
> > > npm ERR! C:\Users\Mahima\AppData\Roaming\npm-cache_logs\2020-06-07T12_59_29_788Z-debug.log
> > 
> >

**Comment by nitindang** [comment]
> > > > Never mind, I figured it out. You need to cd into the directory you're working in! Worked for me.

I think you should also try to add python 2.7 version and then try it in the jpmc directory and tell are you still getting the errors

**Comment by nitindang** [comment]
> > > > Never mind, I figured it out. You need to cd into the directory you're working in! Worked for me.
> > > 
> > > 
> > > I have tried it, now it shows another error
> > > C:\Users\Mahima\JPMC-tech-task-2-PY3>**npm start**
> > > > bank-merge-co-task-2@0.1.0 start C:\Users\Mahima\JPMC-tech-task-2-PY3
> > > > react-scripts start
> > > 
> > > 
> > > 'react-scripts' is not recognized as an internal or external command,
> > > operable program or batch file.
> > > npm ERR! code ELIFECYCLE
> > > npm ERR! errno 1
> > > npm ERR! bank-merge-co-task-2@0.1.0 start: `react-scripts start`
> > > npm ERR! Exit status 1
> > > npm ERR!
> > > npm ERR! Failed at the bank-merge-co-task-2@0.1.0 start script.
> > > npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> > > npm ERR! A complete log of this run can be found in:
> > > npm ERR! C:\Users\Mahima\AppData\Roaming\npm-cache_logs\2020-06-07T12_59_29_788Z-debug.log
> > 
> > 
> > Mahima in which directory you are running the command. Which has the build tools in it ??
> 
> No. I don't know exactly where Build tools installed in the PC as I used Visual Studio installer to install Visual Studio Build Tools 2019 (C++ Build Tools) and I think they are in _C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools._
> 
> ![image](https://user-images.githubusercontent.com/35771912/83971550-7e72d780-a8f9-11ea-96b8-35cd991fc1db.png)
> 
> I run the **npm start** command in the directory in which I cloned JPMC-tech-task-2-PY3 repository for task 2.
> **Where you run it?**

check this https://insidesherpa.s3.amazonaws.com/vinternships/companyassets/Sj7temL583QAYpHXD/setup_devenv_m2_v8.pdf#page=52&zoom=100,0,0
