### ISSUE TITLE
npm start error 

### ISSUE THREAD

**Issue by MahimaJindalMJ** [insidesherpa/JPMC-tech-task-2-PY3#340]
I have tried both latest and v11.0.0 of **node**, same error appears in both of them.

C:\Users\Mahima>**npm install**
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\Mahima\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Mahima\package.json'
npm WARN @angular-devkit/build-angular@0.901.7 requires a peer of @angular/compiler-cli@>=9.0.0 < 10 but none is installed. You must install peer dependencies yourself.
npm WARN @ngtools/webpack@9.1.7 requires a peer of @angular/compiler-cli@>=9.0.0 < 10 but none is installed. You must install peer dependencies yourself.
npm WARN Mahima No description
npm WARN Mahima No repository field.
npm WARN Mahima No README data
npm WARN Mahima No license field.

audited 1877 packages in 21.201s

44 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

C:\Users\Mahima>**npm start**
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Users\Mahima\package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\Mahima\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mahima\AppData\Roaming\npm-cache\_logs\2020-06-07T12_59_50_979Z-debug.log

**Comment by nitindang** [comment]
> I have tried both latest and v11.0.0 of **node**, same error appears in both of them.
> 
> C:\Users\Mahima>**npm install**
> npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\Mahima\package.json'
> npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Mahima\package.json'
> npm WARN @angular-devkit/build-angular@0.901.7 requires a peer of @angular/compiler-cli@>=9.0.0 < 10 but none is installed. You must install peer dependencies yourself.
> npm WARN @ngtools/webpack@9.1.7 requires a peer of @angular/compiler-cli@>=9.0.0 < 10 but none is installed. You must install peer dependencies yourself.
> npm WARN Mahima No description
> npm WARN Mahima No repository field.
> npm WARN Mahima No README data
> npm WARN Mahima No license field.
> 
> audited 1877 packages in 21.201s
> 
> 44 packages are looking for funding
> run `npm fund` for details
> 
> found 0 vulnerabilities
> 
> C:\Users\Mahima>**npm start**
> npm ERR! code ENOENT
> npm ERR! syscall open
> npm ERR! path C:\Users\Mahima\package.json
> npm ERR! errno -4058
> npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\Mahima\package.json'
> npm ERR! enoent This is related to npm not being able to find a file.
> npm ERR! enoent
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users\Mahima\AppData\Roaming\npm-cache_logs\2020-06-07T12_59_50_979Z-debug.log

My current error after running on jpmc directory and even after installing python 2.7

I ran it in the JPMC task 2 directory now but I am still facing these issues

C:\Users\Dell\JPMC-tech-task-2-PY3>npm install

bufferutil@3.0.5 install C:\Users\Dell\JPMC-tech-task-2-PY3\node_modules\bufferutil
prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=11.0.0 runtime=node arch=x64 platform=win32)

C:\Users\Dell\JPMC-tech-task-2-PY3\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Users\Dell\AppData\Roaming\nvm\v11.0.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild ) else (node "C:\Users\Dell\AppData\Roaming\nvm\v11.0.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Traceback (most recent call last):
File "C:\Users\Dell\AppData\Roaming\nvm\v11.0.0\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 16, in
sys.exit(gyp.script_main())
File "C:\Users\Dell\AppData\Roaming\nvm\v11.0.0\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp_init_.py", line 545, in script_main
return main(sys.argv[1:])
File "C:\Users\Dell\AppData\Roaming\nvm\v11.0.0\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp_init_.py", line 538, in main
return gyp_main(args)
File "C:\Users\Dell\AppData\Roaming\nvm\v11.0.0\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp_init_.py", line 514, in gyp_main
options.duplicate_basename_check)
File "C:\Users\Dell\AppData\Roaming\nvm\v11.0.0\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp_init_.py", line 98, in Load
generator.CalculateVariables(default_variables, params)
File "C:\Users\Dell\AppData\Roaming\nvm\v11.0.0\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1916, in CalculateVariables
generator_flags.get('msvs_version', 'auto'))
File "C:\Users\Dell\AppData\Roaming\nvm\v11.0.0\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\MSVSVersion.py", line 434, in SelectVisualStudioVersion
versions = _DetectVisualStudioVersions(version_map[version], 'e' in version)
KeyError: '2019'
gyp ERR! configure error
gyp ERR! stack Error: gyp failed with exit code: 1
gyp ERR! stack at ChildProcess.onCpExit (C:\Users\Dell\AppData\Roaming\nvm\v11.0.0\node_modules\npm\node_modules\node-gyp\lib\configure.js:345:16)
gyp ERR! stack at ChildProcess.emit (events.js:182:13)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\Dell\AppData\Roaming\nvm\v11.0.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Dell\JPMC-tech-task-2-PY3\node_modules\bufferutil
gyp ERR! node -v v11.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN rollback Rolling back node-pre-gyp@0.10.0 failed (this is probably harmless): EPERM: operation not permitted, lstat 'C:\Users\Dell\JPMC-tech-task-2-PY3\node_modules\fsevents\node_modules'
npm WARN bootstrap@4.2.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.2.1 requires a peer of popper.js@^1.14.6 but none is installed. You must install peer dependencies yourself.
npm WARN extract-text-webpack-plugin@3.0.2 requires a peer of webpack@^3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bufferutil@3.0.5 install: prebuild-install || node-gyp rebuild
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bufferutil@3.0.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\Dell\AppData\Roaming\npm-cache_logs\2020-06-07T14_33_42_883Z-debug.log

**Comment by Lethal-Swag** [comment]
same error is mine
![Screenshot (148)](https://user-images.githubusercontent.com/60869913/84587598-2a5a7c80-ae3e-11ea-9547-3ef0968de282.png)

**Comment by Rutuja-divekar** [comment]
I am also facing the same issue

**Comment by Lethal-Swag** [comment]
you have to install nvm using cmd and npm also after that you have to replace file in node_modules then it will be working
have a good day
