### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by hatake-kakashi2202** [insidesherpa/JPMC-tech-task-2-PY3#341]
No data found, generating...                                                                                                                                                                                       Traceback (most recent call last):                                                                                                                                                                                   File "server3.py", line 319, in <module>                                                                                                                                                                             generate_csv()                                                                                                                                                                                                   File "server3.py", line 151, in generate_csv                                                                                                                                                                         writer.writerow([t, stock, side, order, size])                                                                                                                                                                 TypeError: a bytes-like object is required, not 'str'

**Comment by hatake-kakashi2202** [comment]
never mind it resolved itself!!
