### ISSUE TITLE
StopIteration

### ISSUE THREAD

**Issue by Ravipawar143** [insidesherpa/JPMC-tech-task-2-PY3#363]
Traceback (most recent call last):
  File "server3.py", line 320, in <module>
    run(App())
  File "server3.py", line 244, in __init__
    self._sim_start, _, _  = next(self._data_1)
StopIteration

**Comment by bikashhalder** [comment]
@Ravipawar143 I was also having this issue. I sove by copying the test(microsoft excel file) to inside datafeed.. Let me know if it solved it your case too.

**Comment by arosenfeld2003** [comment]
See this solution: https://github.com/insidesherpa/JPMC-tech-task-2-PY3/issues/418
