### ISSUE TITLE
Getting the below error- self._sim_start, _, _  = next(self._data_1)

### ISSUE THREAD

**Issue by heroicshark** [insidesherpa/JPMC-tech-task-2-PY3#418]
C:\Users\shar\jpmc\JPMC-tech-task-2-PY3\datafeed>py server3.py
Traceback (most recent call last):
  File "server3.py", line 320, in <module>
    run(App())
  File "server3.py", line 244, in __init__
    self._sim_start, _, _  = next(self._data_1)
StopIteration

I get this above error and need when  running server3.py and   need help to fix the issue

**Comment by P3NGUIN12** [comment]
Same error

**Comment by juw0n** [comment]
Thank you for this. it solved my issue

**Comment by srujana232** [comment]
![1602840413873409625267963690416](https://user-images.githubusercontent.com/72649102/96241559-f6e05800-0fbf-11eb-8c88-49b1f7ea1b9c.jpg)
I get dis error, help me and solve dis issue

**Comment by destifo** [comment]
Yeah, executing the file from outside the datafeed folder solved my problem. Thanks
