### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by chuksgpfr** [insidesherpa/JPMC-tech-task-2-PY3#462]
Got this error while trying to run server3.py

```
Traceback (most recent call last):
  File "server3.py", line 320, in <module>
    run(App())
  File "server3.py", line 244, in __init__
    self._sim_start, _, _  = next(self._data_1)
StopIteration
```

**Comment by arosenfeld2003** [comment]
I get the same error... did you figure out a fix?

**Comment by arosenfeld2003** [comment]
Solved here: https://github.com/insidesherpa/JPMC-tech-task-2-PY3/issues/418
