### ISSUE TITLE
Error while installing npm in JPMC-tech-task-2-PY3 folder

### ISSUE THREAD

**Issue by saksham02112000** [insidesherpa/JPMC-tech-task-2-PY3#508]
error while running npm install inside folder JPMC-tech-task-2-PY3 folder:
System specifications:
Linux kernel: 5.8.0-53-generic
Linux description: Ubuntu 20.04.2 LTS
node version: v14.17.0
npm version : 7.14.0

```
npm ERR! code 1
npm ERR! path /home/saksham/JPMC-tech-task-2-PY3/node_modules/bufferutil
npm ERR! command failed
npm ERR! command sh -c prebuild-install || node-gyp rebuild
npm ERR! make: Entering directory '/home/saksham/JPMC-tech-task-2-PY3/node_modules/bufferutil/build'
npm ERR!   CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
npm ERR! make: Leaving directory '/home/saksham/JPMC-tech-task-2-PY3/node_modules/bufferutil/build'
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@14.17.0 | linux | x64
npm ERR! gyp info find Python using Python version 3.8.5 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/saksham/JPMC-tech-task-2-PY3/node_modules/bufferutil/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/saksham/.cache/node-gyp/14.17.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/saksham/.cache/node-gyp/14.17.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/saksham/.cache/node-gyp/14.17.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/saksham/JPMC-tech-task-2-PY3/node_modules/bufferutil',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! In file included from ../node_modules/nan/nan_converters.h:67,
npm ERR!                  from ../node_modules/nan/nan.h:202,
npm ERR!                  from ../src/bufferutil.cc:7:
npm ERR! ../node_modules/nan/nan_converters_43_inl.h: In static member function ‘static Nan::imp::ToFactoryBase<v8::Boolean>::return_t Nan::imp::ToFactory<v8::Boolean>::convert(v8::Local<v8::Value>)’:
npm ERR! ../node_modules/nan/nan_converters_43_inl.h:18:49: error: cannot convert ‘v8::Local<v8::Context>’ to ‘v8::Isolate*’
npm ERR!    18 |       val->To ## TYPE(isolate->GetCurrentContext())                            \
npm ERR!       |                       ~~~~~~~~~~~~~~~~~~~~~~~~~~^~
npm ERR!       |                                                 |
npm ERR!       |                                                 v8::Local<v8::Context>
npm ERR! ../node_modules/nan/nan_converters_43_inl.h:22:1: note: in expansion of macro ‘X’
npm ERR!    22 | X(Boolean)
npm ERR!       | ^
npm ERR! In file included from /home/saksham/.cache/node-gyp/14.17.0/include/node/node.h:67,
npm ERR!                  from ../node_modules/nan/nan.h:51,
npm ERR!                  from ../src/bufferutil.cc:7:
npm ERR! /home/saksham/.cache/node-gyp/14.17.0/include/node/v8.h:2848:37: note:   initializing argument 1 of ‘v8::Local<v8::Boolean> v8::Value::ToBoolean(v8::Isolate*) const’
npm ERR!  2848 |   Local<Boolean> ToBoolean(Isolate* isolate) const;
npm ERR!       |                            ~~~~~~~~~^~~~~~~
npm ERR! In file included from ../node_modules/nan/nan_converters.h:67,
npm ERR!                  from ../node_modules/nan/nan.h:202,
npm ERR!                  from ../src/bufferutil.cc:7:
npm ERR! ../node_modules/nan/nan_converters_43_inl.h: In static member function ‘static Nan::imp::ValueFactoryBase<bool>::return_t Nan::imp::ToFactory<bool>::convert(v8::Local<v8::Value>)’:
npm ERR! ../node_modules/nan/nan_converters_43_inl.h:37:55: error: cannot convert ‘v8::Local<v8::Context>’ to ‘v8::Isolate*’
npm ERR!    37 |   return val->NAME ## Value(isolate->GetCurrentContext());                     \
npm ERR!       |                             ~~~~~~~~~~~~~~~~~~~~~~~~~~^~
npm ERR!       |                                                       |
npm ERR!       |                                                       v8::Local<v8::Context>
npm ERR! ../node_modules/nan/nan_converters_43_inl.h:40:1: note: in expansion of macro ‘X’
npm ERR!    40 | X(bool, Boolean)
npm ERR!       | ^
npm ERR! In file included from /home/saksham/.cache/node-gyp/14.17.0/include/node/node.h:67,
npm ERR!                  from ../node_modules/nan/nan.h:51,
npm ERR!                  from ../src/bufferutil.cc:7:
npm ERR! /home/saksham/.cache/node-gyp/14.17.0/include/node/v8.h:2858:30: note:   initializing argument 1 of ‘bool v8::Value::BooleanValue(v8::Isolate*) const’
npm ERR!  2858 |   bool BooleanValue(Isolate* isolate) const;
npm ERR!       |                     ~~~~~~~~~^~~~~~~
npm ERR! In file included from ../node_modules/nan/nan_new.h:189,
npm ERR!                  from ../node_modules/nan/nan.h:203,
npm ERR!                  from ../src/bufferutil.cc:7:
npm ERR! ../node_modules/nan/nan_implementation_12_inl.h: In static member function ‘static Nan::imp::FactoryBase<v8::Function>::return_t Nan::imp::Factory<v8::Function>::New(Nan::FunctionCallback, v8::Local<v8::Value>)’:
npm ERR! ../node_modules/nan/nan_implementation_12_inl.h:103:42: error: cannot convert ‘v8::Isolate*’ to ‘v8::Local<v8::Context>’
npm ERR!   103 |   return scope.Escape(v8::Function::New( isolate
npm ERR!       |                                          ^~~~~~~
npm ERR!       |                                          |
npm ERR!       |                                          v8::Isolate*
npm ERR! In file included from /home/saksham/.cache/node-gyp/14.17.0/include/node/node.h:67,
npm ERR!                  from ../node_modules/nan/nan.h:51,
npm ERR!                  from ../src/bufferutil.cc:7:
npm ERR! /home/saksham/.cache/node-gyp/14.17.0/include/node/v8.h:4446:22: note:   initializing argument 1 of ‘static v8::MaybeLocal<v8::Function> v8::Function::New(v8::Local<v8::Context>, v8::FunctionCallback, v8::Local<v8::Value>, int, v8::ConstructorBehavior, v8::SideEffectType)’
npm ERR!  4446 |       Local<Context> context, FunctionCallback callback,
npm ERR!       |       ~~~~~~~~~~~~~~~^~~~~~~
npm ERR! In file included from ../node_modules/nan/nan_new.h:189,
npm ERR!                  from ../node_modules/nan/nan.h:203,
npm ERR!                  from ../src/bufferutil.cc:7:
npm ERR! ../node_modules/nan/nan_implementation_12_inl.h: In static member function ‘static Nan::imp::FactoryBase<v8::StringObject>::return_t Nan::imp::Factory<v8::StringObject>::New(v8::Local<v8::String>)’:
npm ERR! ../node_modules/nan/nan_implementation_12_inl.h:337:37: error: no matching function for call to ‘v8::StringObject::New(v8::Local<v8::String>&)’
npm ERR!   337 |   return v8::StringObject::New(value).As<v8::StringObject>();
npm ERR!       |                                     ^
npm ERR! In file included from /home/saksham/.cache/node-gyp/14.17.0/include/node/node.h:67,
npm ERR!                  from ../node_modules/nan/nan.h:51,
npm ERR!                  from ../src/bufferutil.cc:7:
npm ERR! /home/saksham/.cache/node-gyp/14.17.0/include/node/v8.h:5854:23: note: candidate: ‘static v8::Local<v8::Value> v8::StringObject::New(v8::Isolate*, v8::Local<v8::String>)’
npm ERR!  5854 |   static Local<Value> New(Isolate* isolate, Local<String> value);
npm ERR!       |                       ^~~
npm ERR! /home/saksham/.cache/node-gyp/14.17.0/include/node/v8.h:5854:23: note:   candidate expects 2 arguments, 1 provided
npm ERR! In file included from ../node_modules/nan/nan_new.h:189,
npm ERR!                  from ../node_modules/nan/nan.h:203,
npm ERR!                  from ../src/bufferutil.cc:7:
npm ERR! ../node_modules/nan/nan_implementation_12_inl.h:337:58: error: expected primary-expression before ‘>’ token
npm ERR!   337 |   return v8::StringObject::New(value).As<v8::StringObject>();
npm ERR!       |                                                          ^
npm ERR! ../node_modules/nan/nan_implementation_12_inl.h:337:60: error: expected primary-expression before ‘)’ token
npm ERR!   337 |   return v8::StringObject::New(value).As<v8::StringObject>();
npm ERR!       |                                                            ^
npm ERR! In file included from ../src/bufferutil.cc:7:
npm ERR! ../node_modules/nan/nan.h: In constructor ‘Nan::Utf8String::Utf8String(v8::Local<v8::Value>)’:
npm ERR! ../node_modules/nan/nan.h:1034:53: error: no matching function for call to ‘v8::Value::ToString()’
npm ERR!  1034 |       v8::Local<v8::String> string = from->ToString();
npm ERR!       |                                                     ^
npm ERR! In file included from /home/saksham/.cache/node-gyp/14.17.0/include/node/node.h:67,
npm ERR!                  from ../node_modules/nan/nan.h:51,
npm ERR!                  from ../src/bufferutil.cc:7:
npm ERR! /home/saksham/.cache/node-gyp/14.17.0/include/node/v8.h:2810:44: note: candidate: ‘v8::MaybeLocal<v8::String> v8::Value::ToString(v8::Local<v8::Context>) const’
npm ERR!  2810 |   V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
npm ERR!       |                                            ^~~~~~~~
npm ERR! /home/saksham/.cache/node-gyp/14.17.0/include/node/v8.h:2810:44: note:   candidate expects 1 argument, 0 provided
npm ERR! In file included from ../src/bufferutil.cc:7:
npm ERR! ../node_modules/nan/nan.h:1044:37: error: cannot convert ‘char*’ to ‘v8::Isolate*’
npm ERR!  1044 |         length_ = string->WriteUtf8(str_, static_cast<int>(len), 0, flags);
npm ERR!       |                                     ^~~~
npm ERR!       |                                     |
npm ERR!       |                                     char*
npm ERR! In file included from /home/saksham/.cache/node-gyp/14.17.0/include/node/node.h:67,
npm ERR!                  from ../node_modules/nan/nan.h:51,
npm ERR!                  from ../src/bufferutil.cc:7:
npm ERR! /home/saksham/.cache/node-gyp/14.17.0/include/node/v8.h:3037:26: note:   initializing argument 1 of ‘int v8::String::WriteUtf8(v8::Isolate*, char*, int, int*, int) const’
npm ERR!  3037 |   int WriteUtf8(Isolate* isolate, char* buffer, int length = -1,
npm ERR!       |                 ~~~~~~~~~^~~~~~~
npm ERR! In file included from ../src/bufferutil.cc:7:
npm ERR! ../node_modules/nan/nan.h: In member function ‘void Nan::AsyncWorker::SaveToPersistent(const char*, const v8::Local<v8::Value>&)’:
npm ERR! ../node_modules/nan/nan.h:1818:64: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, const v8::Local<v8::Value>&)’
npm ERR!  1818 |     New(persistentHandle)->Set(New(key).ToLocalChecked(), value);
npm ERR!       |                                                                ^
npm ERR! In file included from /home/saksham/.cache/node-gyp/14.17.0/include/node/node.h:67,
npm ERR!                  from ../node_modules/nan/nan.h:51,
npm ERR!                  from ../src/bufferutil.cc:7:
npm ERR! /home/saksham/.cache/node-gyp/14.17.0/include/node/v8.h:3670:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
npm ERR!  3670 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
npm ERR!       |                                     ^~~
npm ERR! /home/saksham/.cache/node-gyp/14.17.0/include/node/v8.h:3670:37: note:   candidate expects 3 arguments, 2 provided
npm ERR! /home/saksham/.cache/node-gyp/14.17.0/include/node/v8.h:3673:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
npm ERR!  3673 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
npm ERR!       |                                     ^~~
npm ERR! /home/saksham/.cache/node-gyp/14.17.0/include/node/v8.h:3673:37: note:   candidate expects 3 arguments, 2 provided
npm ERR! In file included from ../src/bufferutil.cc:7:
npm ERR! ../node_modules/nan/nan.h: In member function ‘void Nan::AsyncWorker::SaveToPersistent(const v8::Local<v8::String>&, const v8::Local<v8::Value>&)’:
npm ERR! ../node_modules/nan/nan.h:1824:42: error: no matching function for call to ‘v8::Object::Set(const v8::Local<v8::String>&, const v8::Local<v8::Value>&)’
npm ERR!  1824 |     New(persistentHandle)->Set(key, value);
npm ERR!       |                                          ^
npm ERR! In file included from /home/saksham/.cache/node-gyp/14.17.0/include/node/node.h:67,
npm ERR!                  from ../node_modules/nan/nan.h:51,
npm ERR!                  from ../src/bufferutil.cc:7:
npm ERR! /home/saksham/.cache/node-gyp/14.17.0/include/node/v8.h:3670:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
npm ERR!  3670 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
npm ERR!       |                                     ^~~
npm ERR! /home/saksham/.cache/node-gyp/14.17.0/include/node/v8.h:3670:37: note:   candidate expects 3 arguments, 2 provided
npm ERR! /home/saksham/.cache/node-gyp/14.17.0/include/node/v8.h:3673:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
npm ERR!  3673 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
npm ERR!       |                                     ^~~
npm ERR! /home/saksham/.cache/node-gyp/14.17.0/include/node/v8.h:3673:37: note:   candidate expects 3 arguments, 2 provided
npm ERR! In file included from ../src/bufferutil.cc:7:
npm ERR! ../node_modules/nan/nan.h: In member function ‘void Nan::AsyncWorker::SaveToPersistent(uint32_t, const v8::Local<v8::Value>&)’:
npm ERR! ../node_modules/nan/nan.h:1830:44: error: no matching function for call to ‘v8::Object::Set(uint32_t&, const v8::Local<v8::Value>&)’
npm ERR!  1830 |     New(persistentHandle)->Set(index, value);
npm ERR!       |                                            ^
npm ERR! In file included from /home/saksham/.cache/node-gyp/14.17.0/include/node/node.h:67,
npm ERR!                  from ../node_modules/nan/nan.h:51,
npm ERR!                  from ../src/bufferutil.cc:7:
npm ERR! /home/saksham/.cache/node-gyp/14.17.0/include/node/v8.h:3670:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
npm ERR!  3670 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
npm ERR!       |                                     ^~~
npm ERR! /home/saksham/.cache/node-gyp/14.17.0/include/node/v8.h:3670:37: note:   candidate expects 3 arguments, 2 provided
npm ERR! /home/saksham/.cache/node-gyp/14.17.0/include/node/v8.h:3673:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
npm ERR!  3673 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
npm ERR!       |                                     ^~~
npm ERR! /home/saksham/.cache/node-gyp/14.17.0/include/node/v8.h:3673:37: note:   candidate expects 3 arguments, 2 provided
npm ERR! In file included from ../src/bufferutil.cc:7:
npm ERR! ../node_modules/nan/nan.h: In member function ‘v8::Local<v8::Value> Nan::AsyncWorker::GetFromPersistent(const char*) const’:
npm ERR! ../node_modules/nan/nan.h:1836:61: error: no matching function for call to ‘v8::Object::Get(v8::Local<v8::String>)’
npm ERR!  1836 |         New(persistentHandle)->Get(New(key).ToLocalChecked()));
npm ERR!       |                                                             ^
npm ERR! In file included from /home/saksham/.cache/node-gyp/14.17.0/include/node/node.h:67,
npm ERR!                  from ../node_modules/nan/nan.h:51,
npm ERR!                  from ../src/bufferutil.cc:7:
npm ERR! /home/saksham/.cache/node-gyp/14.17.0/include/node/v8.h:3717:43: note: candidate: ‘v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, v8::Local<v8::Value>)’
npm ERR!  3717 |   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
npm ERR!       |                                           ^~~
npm ERR! /home/saksham/.cache/node-gyp/14.17.0/include/node/v8.h:3717:43: note:   candidate expects 2 arguments, 1 provided
npm ERR! /home/saksham/.cache/node-gyp/14.17.0/include/node/v8.h:3720:43: note: candidate: ‘v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, uint32_t)’
npm ERR!  3720 |   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
npm ERR!       |                                           ^~~
npm ERR! /home/saksham/.cache/node-gyp/14.17.0/include/node/v8.h:3720:43: note:   candidate expects 2 arguments, 1 provided
npm ERR! In file included from ../src/bufferutil.cc:7:
npm ERR! ../node_modules/nan/nan.h: In member function ‘v8::Local<v8::Value> Nan::AsyncWorker::GetFromPersistent(const v8::Local<v8::String>&) const’:
npm ERR! ../node_modules/nan/nan.h:1842:55: error: no matching function for call to ‘v8::Object::Get(const v8::Local<v8::String>&)’
npm ERR!  1842 |     return scope.Escape(New(persistentHandle)->Get(key));
npm ERR!       |                                                       ^
npm ERR! In file included from /home/saksham/.cache/node-gyp/14.17.0/include/node/node.h:67,
npm ERR!                  from ../node_modules/nan/nan.h:51,
npm ERR!                  from ../src/bufferutil.cc:7:
npm ERR! /home/saksham/.cache/node-gyp/14.17.0/include/node/v8.h:3717:43: note: candidate: ‘v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, v8::Local<v8::Value>)’
npm ERR!  3717 |   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
npm ERR!       |                                           ^~~
npm ERR! /home/saksham/.cache/node-gyp/14.17.0/include/node/v8.h:3717:43: note:   candidate expects 2 arguments, 1 provided
npm ERR! /home/saksham/.cache/node-gyp/14.17.0/include/node/v8.h:3720:43: note: candidate: ‘v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, uint32_t)’
npm ERR!  3720 |   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
npm ERR!       |                                           ^~~
npm ERR! /home/saksham/.cache/node-gyp/14.17.0/include/node/v8.h:3720:43: note:   candidate expects 2 arguments, 1 provided
npm ERR! In file included from ../src/bufferutil.cc:7:
npm ERR! ../node_modules/nan/nan.h: In member function ‘v8::Local<v8::Value> Nan::AsyncWorker::GetFromPersistent(uint32_t) const’:
npm ERR! ../node_modules/nan/nan.h:1847:57: error: no matching function for call to ‘v8::Object::Get(uint32_t&)’
npm ERR!  1847 |     return scope.Escape(New(persistentHandle)->Get(index));
npm ERR!       |                                                         ^
npm ERR! In file included from /home/saksham/.cache/node-gyp/14.17.0/include/node/node.h:67,
npm ERR!                  from ../node_modules/nan/nan.h:51,
npm ERR!                  from ../src/bufferutil.cc:7:
npm ERR! /home/saksham/.cache/node-gyp/14.17.0/include/node/v8.h:3717:43: note: candidate: ‘v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, v8::Local<v8::Value>)’
npm ERR!  3717 |   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
npm ERR!       |                                           ^~~
npm ERR! /home/saksham/.cache/node-gyp/14.17.0/include/node/v8.h:3717:43: note:   candidate expects 2 arguments, 1 provided
npm ERR! /home/saksham/.cache/node-gyp/14.17.0/include/node/v8.h:3720:43: note: candidate: ‘v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, uint32_t)’
npm ERR!  3720 |   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
npm ERR!       |                                           ^~~
npm ERR! /home/saksham/.cache/node-gyp/14.17.0/include/node/v8.h:3720:43: note:   candidate expects 2 arguments, 1 provided
npm ERR! In file included from ../src/bufferutil.cc:7:
npm ERR! ../node_modules/nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
npm ERR! ../node_modules/nan/nan.h:2167:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
npm ERR!  2167 |     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
npm ERR!       |                                                              ^
npm ERR! In file included from /usr/include/c++/9/cassert:44,
npm ERR!                  from /home/saksham/.cache/node-gyp/14.17.0/include/node/node_object_wrap.h:26,
npm ERR!                  from ../node_modules/nan/nan.h:53,
npm ERR!                  from ../src/bufferutil.cc:7:
npm ERR! ../node_modules/nan/nan_object_wrap.h: In destructor ‘virtual Nan::ObjectWrap::~ObjectWrap()’:
npm ERR! ../node_modules/nan/nan_object_wrap.h:24:25: error: ‘class Nan::Persistent<v8::Object>’ has no member named ‘IsNearDeath’
npm ERR!    24 |     assert(persistent().IsNearDeath());
npm ERR!       |                         ^~~~~~~~~~~
npm ERR! In file included from ../node_modules/nan/nan.h:2657,
npm ERR!                  from ../src/bufferutil.cc:7:
npm ERR! ../node_modules/nan/nan_object_wrap.h: In member function ‘void Nan::ObjectWrap::MakeWeak()’:
npm ERR! ../node_modules/nan/nan_object_wrap.h:67:18: error: ‘class Nan::Persistent<v8::Object>’ has no member named ‘MarkIndependent’
npm ERR!    67 |     persistent().MarkIndependent();
npm ERR!       |                  ^~~~~~~~~~~~~~~
npm ERR! In file included from /usr/include/c++/9/cassert:44,
npm ERR!                  from /home/saksham/.cache/node-gyp/14.17.0/include/node/node_object_wrap.h:26,
npm ERR!                  from ../node_modules/nan/nan.h:53,
npm ERR!                  from ../src/bufferutil.cc:7:
npm ERR! ../node_modules/nan/nan_object_wrap.h: In static member function ‘static void Nan::ObjectWrap::WeakCallback(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’:
npm ERR! ../node_modules/nan/nan_object_wrap.h:124:26: error: ‘class Nan::Persistent<v8::Object>’ has no member named ‘IsNearDeath’
npm ERR!   124 |     assert(wrap->handle_.IsNearDeath());
npm ERR!       |                          ^~~~~~~~~~~
npm ERR! ../src/bufferutil.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE mask(Nan::NAN_METHOD_ARGS_TYPE)’:
npm ERR! ../src/bufferutil.cc:12:64: error: no matching function for call to ‘v8::Value::Int32Value()’
npm ERR!    12 |   char* to = node::Buffer::Data(info[2]) + info[3]->Int32Value();
npm ERR!       |                                                                ^
npm ERR! In file included from /home/saksham/.cache/node-gyp/14.17.0/include/node/node.h:67,
npm ERR!                  from ../node_modules/nan/nan.h:51,
npm ERR!                  from ../src/bufferutil.cc:7:
npm ERR! /home/saksham/.cache/node-gyp/14.17.0/include/node/v8.h:2869:40: note: candidate: ‘v8::Maybe<int> v8::Value::Int32Value(v8::Local<v8::Context>) const’
npm ERR!  2869 |   V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
npm ERR!       |                                        ^~~~~~~~~~
npm ERR! /home/saksham/.cache/node-gyp/14.17.0/include/node/v8.h:2869:40: note:   candidate expects 1 argument, 0 provided
npm ERR! ../src/bufferutil.cc:13:39: error: no matching function for call to ‘v8::Value::Int32Value()’
npm ERR!    13 |   size_t length = info[4]->Int32Value();
npm ERR!       |                                       ^
npm ERR! In file included from /home/saksham/.cache/node-gyp/14.17.0/include/node/node.h:67,
npm ERR!                  from ../node_modules/nan/nan.h:51,
npm ERR!                  from ../src/bufferutil.cc:7:
npm ERR! /home/saksham/.cache/node-gyp/14.17.0/include/node/v8.h:2869:40: note: candidate: ‘v8::Maybe<int> v8::Value::Int32Value(v8::Local<v8::Context>) const’
npm ERR!  2869 |   V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
npm ERR!       |                                        ^~~~~~~~~~
npm ERR! /home/saksham/.cache/node-gyp/14.17.0/include/node/v8.h:2869:40: note:   candidate expects 1 argument, 0 provided
npm ERR! In file included from ../node_modules/nan/nan.h:51,
npm ERR!                  from ../src/bufferutil.cc:7:
npm ERR! ../src/bufferutil.cc: At global scope:
npm ERR! /home/saksham/.cache/node-gyp/14.17.0/include/node/node.h:758:43: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
npm ERR!   758 |       (node::addon_register_func) (regfunc),                          \
npm ERR!       |                                           ^
npm ERR! /home/saksham/.cache/node-gyp/14.17.0/include/node/node.h:792:3: note: in expansion of macro ‘NODE_MODULE_X’
npm ERR!   792 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
npm ERR!       |   ^~~~~~~~~~~~~
npm ERR! ../src/bufferutil.cc:113:1: note: in expansion of macro ‘NODE_MODULE’
npm ERR!   113 | NODE_MODULE(bufferutil, init)
npm ERR!       | ^~~~~~~~~~~
npm ERR! make: *** [bufferutil.target.mk:111: Release/obj.target/bufferutil/src/bufferutil.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:376:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
npm ERR! gyp ERR! System Linux 5.8.0-53-generic
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /home/saksham/JPMC-tech-task-2-PY3/node_modules/bufferutil
npm ERR! gyp ERR! node -v v14.17.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/saksham/.npm/_logs/2021-06-02T09_06_00_865Z-debug.log

```

**Comment by sydgible** [comment]
hey, i had this issue as well, but on windows.

try setting your npm config, or set your python alias to point to python2.7.
'npm config set python c:\python27\python.exe' or whatever the path is to your python2.7.  i think node-gyp relies on python2.7.
double check npm configs
'npm config list'

and i stuck with node 11.0.0 and npm 6.4.1, since that's what the project used 

check with:
'node -v'
'npm -v'
if different, run:
'nvm install v11.0.0'
'nvm use 11.0.0'

then run 'npm install'
had a bunch of warnings, but it completed.

**Comment by saksham02112000** [comment]
[image: image.png]Hey thanks for your suggeestions.  I tried whatyou said
then i got this error.

**Comment by saksham02112000** [comment]
Hey thanks!! I tried what you said changed node and npm version to 11.0.0 and 6..4.1 respectively But got error while npm install.
![Screenshot_20210602_234359](https://user-images.githubusercontent.com/55004186/120531735-955ce480-c3fc-11eb-8ef1-5d11d4cbdb3b.png)

**Comment by sydgible** [comment]
since you're on linux your python2.7 is probably at /usr/bin/python27 instead of c:\python27\python.exe
check where your python is and put that directory in this command
'npm config set python _replace_with_directory_to_your_python_'

**Comment by Ruben304** [comment]
did yall figure out this error? I'm having the same problem
