### ISSUE TITLE
Syntax Error: JSON Parse Error: Unexpected EOF 

### ISSUE THREAD

**Issue by 20nikhitak** [insidesherpa/JPMC-tech-task-2-PY3#522]
<img width="1032" alt="Screen Shot 2021-07-25 at 2 48 41 PM" src="https://user-images.githubusercontent.com/52051441/126914502-8eeee2b7-df6b-40c2-aeec-9dc3318a909f.png">

I am seeing an unexpected EOF when I run the bank streaming data - I did not make any changes to the code, I am just running it. This is the message I see in my terminal: 

Exception happened during processing of request from ('127.0.0.1', 65321)
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "datafeed/server3.py", line 213, in do_GET
    get(self, routes)
  File "datafeed/server3.py", line 202, in get
    req_handler.wfile.write(bytes(data,  encoding = 'utf-8'))
TypeError: str() takes at most 1 argument (2 given)

Please let me know what to edit in the code to make it work.

**Comment by bmabioye** [comment]
you were running python 2.7 server instead of python3 server

run
python3 datafeed/server3.py

fix this issue.
