### ISSUE TITLE
Stop Iteration error while attempting to run server3.py

### ISSUE THREAD

**Issue by federicodzf** [insidesherpa/JPMC-tech-task-2-PY3#586]
![image](https://user-images.githubusercontent.com/102984566/177126121-d83376cd-ec5a-435a-8b03-34749476a786.png)
```
Traceback (most recent call last):
  File "C:\Users\feder\Desktop\JPMorganChase\JPMC-tech-task-2-PY3\datafeed\server3.py", line 320, in <module>
    run(App())
  File "C:\Users\feder\Desktop\JPMorganChase\JPMC-tech-task-2-PY3\datafeed\server3.py", line 244, in __init__
    self._sim_start, _, _  = next(self._data_1)
StopIteration
```

There appears to be an issue when I try running the server that I cannot fix. I tried changing the port to 8085 in the file, but it did not change anything. I am confused as there is no information regarding this problem, and I really do not know what it means. Please let me know what I should do. 

I am working with a HP Envy laptop running Windows 11 and Python version 3.9.11

**Comment by federicodzf** [comment]
I think I fixed the issue. I was running the server3.py file within datafeed directory instead of running python datafeed/server3.py
