### ISSUE TITLE
StopIteration error when i try to run the server

### ISSUE THREAD

**Issue by whotterre** [insidesherpa/JPMC-tech-task-2-PY3#633]
When i try running the server on Python 3.10.0, I get the following error:
Traceback (most recent call last):
  File "/home/jai/Downloads/Web Dev/forage-jpmc-swe-task-2/datafeed/server3.py", line 342, in <module>
    run(App())
  File "/home/jai/Downloads/Web Dev/forage-jpmc-swe-task-2/datafeed/server3.py", line 265, in __init__
    self._sim_start,_,_ = next(self._data_1)
StopIteration

**Comment by MohitDingal** [comment]
Did you find any solution for this?

**Comment by whotterre** [comment]
Yes, but it's been a while since then

**Comment by Melsa16** [comment]
I have the same error. Could you please help?
