### ISSUE TITLE
error in starting npm in windows 10. please suggest solution.

### ISSUE THREAD

**Issue by Shiwani19890** [insidesherpa/JPMC-tech-task-2-PY3#94]
`
C:\Users\Win10>node -v
v11.0.0

C:\Users\Win10>npm -v
internal/modules/cjs/loader.js:589
    throw err;
    ^

Error: Cannot find module 'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:760:12)
    at startup (internal/bootstrap/node.js:303:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:872:3)
internal/modules/cjs/loader.js:589
    throw err;
    ^

Error: Cannot find module 'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:760:12)
    at startup (internal/bootstrap/node.js:303:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:872:3)

C:\Users\Win10>`

**Comment by Manishmkk** [comment]
i think use to try to reinstall the nvm and npm

**Comment by rishab0914** [comment]
when i am typing command node -v its displaying this app cannot ru on this pc

**Comment by sanyadeveloper2000** [comment]
![Screenshot (110)](https://user-images.githubusercontent.com/47472176/81003171-0b90bf80-8e68-11ea-9024-849ed2af58c7.png)
![Screenshot (111)](https://user-images.githubusercontent.com/47472176/81003183-0e8bb000-8e68-11ea-9279-cc6930fff60c.png)

Please help with this error

**Comment by prafful98** [comment]
@sanyadeveloper2000 you can resolve all dependency issues by running `npm install` in project directory.

**Comment by SiddhlodaAyyar** [comment]
Watch this video and if you still get the error comment down in the youtube section and we'll try to solve it.
https://youtu.be/wRAG9i8O_44
